openapi: '3.0.2'
info:
  title: openAPI specification
  version: '1.0'

tags:
  - name: Аутентификация
  - name: Восстановление пароля

paths:
  /log-in:
    $ref: "paths/log_in.yml"
  /log-out:
    $ref: "paths/log_out.yml"
  /change-password:
    $ref: "paths/change_password.yml"
  /send_recovery_letter:
    $ref: "paths/send_recovery_letter.yml"
  /check_recovery_token:
    $ref: "paths/check_recovery_token.yml"